### ISSUE TITLE
Service not respecting rtc allow all

### ISSUE THREAD

**Issue by MartinN3** [benx203/aria2installer-Windows#1]
Hello, first of all thank you for great package.

I'm having issue that my aria2 service doesn't respect some options in aria2.config. but works when i run it manually and specify aria2c --enable-rpc --rpc-listen-all

Thanks

**Comment by benx203** [comment]
Hi!
You can try modify the start argument in aria2-winsw.xml and rebuild.
Or after installed,find aria2-winsw.xml  file and add start argument like this:
`<startargument>--enable-rpc</startargument>`
`<startargument>--rpc-listen-all</startargument>`
